services:
  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: MatKhauManh123
      POSTGRES_DB: quizdb
    volumes:
      - devdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdevdata:/data
volumes:
  devdata:
  redisdevdata:
